### ISSUE TITLE
decentraland@0.5.5 Error: Cannot find module 'pg'

### ISSUE THREAD

**Issue by rushughes** [decentraland/cli#122]
did an

`npm install -g decentraland`

now when running dcl init i get

`cool-2:dcl-2018-03-29 rus$ dcl init
module.js:538
    throw err;
    ^

Error: Cannot find module 'pg'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rus/.nvm/versions/node/v8.9.1/lib/node_modules/decentraland/node_modules/decentraland-commons/dist/db/postgres.js:8:11)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)`

`cool-2:dcl-2018-03-29 rus$ node -v
v8.9.1
cool-2:dcl-2018-03-29 rus$ npm -v
5.5.1`

**Comment by menduz** [comment]
We will fix this soon

**Comment by yemel** [comment]
Hey @rushughes, looks like @menduz fixed the bug two days ago in [this commit](https://github.com/decentraland/cli/commit/3deb33ff0226f03d35891e1f027545c7bb107179).

Try this:
```
npm uninstall -g decentraland
npm i -g decentraland@0.6.1
```

**Comment by HAZARDU5** [comment]
Same problem here on a fresh install. I'll probably wait until this is officially fixed.
