### ISSUE TITLE
Weird installation issue on macOs High Sierra. 

### ISSUE THREAD

**Issue by leobelen** [decentraland/cli#159]
Trying to execute 'npm install decentraland' on macOs High Sierra and node.js 10.0.1 fails with errors, however, if node.js 6 is used, the SDK can be installed. Interestingly enough, once installed in such way, it is not possible to run 'dcl' due to imcompatibility issues. 

```
--Errors of Decentraland Installation on node.js 10.0.1
  LIBTOOL-STATIC Release/hidapi.a
  CXX(target) Release/obj.target/HID/src/HID.o
../src/HID.cc:207:45: error: no matching member function for call to
      'NewInstance'
    Local<Object> buf = nodeBufConstructor->NewInstance(1, nodeBufferArgs);
                        ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/Users/leobelen/.node-gyp/10.1.0/include/node/v8.h:3851:44: note: candidate
      function not viable: requires single argument 'context', but 2 arguments
      were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/leobelen/.node-gyp/10.1.0/include/node/v8.h:3848:44: note: candidate
      function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/HID.cc:231:20: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  iocb->_callback->Call(2, argv);
                   ^
../../nan/nan.h:1617:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:98:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/HID.cc:409:37: warning: 'Value' is deprecated [-Wdeprecated-declarations]
        serialPointer = (wchar_t*) *v8::String::Value(info[2]);
                                    ^
/Users/leobelen/.node-gyp/10.1.0/include/node/v8.h:2846:5: note: 'Value' has
      been explicitly marked deprecated here
    V8_DEPRECATED("Use Isolate version", explicit Value(Local<v8::Value> obj));
    ^
/Users/leobelen/.node-gyp/10.1.0/include/node/v8config.h:321:29: note: expanded
      from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
2 warnings and 1 error generated.
make: *** [Release/obj.target/HID/src/HID.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Darwin 17.5.0
gyp ERR! command "/usr/local/Cellar/node/10.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/decentraland/node_modules/node-hid
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-hid@0.6.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-hid@0.6.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

--- Errors of running 'dcl' on node.js 6
/usr/local/lib/node_modules/decentraland/dist/utils/filesystem.js:13
exports.pathExists = util_1.promisify(fs.pathExists);
                            ^

TypeError: util_1.promisify is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/decentraland/dist/utils/filesystem.js:13:29)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/decentraland/dist/utils/dclinfo.js:12:22)
    at Module._compile (module.js:577:32)
```

**Comment by menduz** [comment]
Use node 8

**Comment by sneak** [comment]
Ran into this myself today on v10.1.0, adding a +1 for support of this version

**Comment by belohlavek** [comment]
Working on it, expect node 10 support soon.

**Comment by belohlavek** [comment]
@rc includes node 10 support, please test it if you can :)

**Comment by lylepratt** [comment]
Having this same problem and don't want to downgrade my whole system to node8. How can I test the new version?

**Comment by belohlavek** [comment]
check the latest release!

**Comment by leobelen** [comment]
Now it seems to work... thanks!
