### ISSUE TITLE
TypeError: a is not a constructor - createFSEventsInstance

### ISSUE THREAD

**Issue by negue** [decentraland/cli#488]
# What? 

Just installed `npm install -g decentraland`, created a project with `dcl init`

`dcl start` results in:

```
TypeError: a is not a constructor
    at createFSEventsInstance (/usr/local/lib/node_modules/decentraland/dist/cli/index.js:1:2452510)
    at setFSEventsListener (/usr/local/lib/node_modules/decentraland/dist/cli/index.js:1:2453047)
    at FSWatcher.FsEventsHandler._watchWithFsEvents (/usr/local/lib/node_modules/decentraland/dist/cli/index.js:1:2455317)
    at FSWatcher.<anonymous> (/usr/local/lib/node_modules/decentraland/dist/cli/index.js:1:2457088)
    at LOOP (fs.js:1576:14)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

OS: Mac
Node: v12.8.1

Is the node version too new?

**Comment by negue** [comment]
Fixed with `npm uninstall -g fsevents` :)
