### ISSUE TITLE
Error when running `dcl init`

### ISSUE THREAD

**Issue by HAZARDU5** [decentraland/cli#67]
I'm getting the following error when running `dcl init` after installing the cli globally using `sudo npm install -g decentraland`:

```
/usr/local/lib/node_modules/decentraland/dist/index.js:18
    init(options = {}) {
                 ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/decentraland/bin/dcl:5:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

Pretty sure the above syntax isn't allowed in ES6. What specific node version does the cli require?

I'm running Windows 10 64-bit and have the cli installed inside the bash subsystem.

**Comment by michaltakac** [comment]
This syntax is not allowed in ES5 but I's part of the ES6 spec - `default parameters` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

What is your `node` version (`node -v`)?

It seems like we need to define the lowest node version we support in `package.json`.

**Comment by HAZARDU5** [comment]
Tested again and things seem to work now on vanilla Windows 10 with node.js 8 LTS, and `windows-build-tools` installed.
