### ISSUE TITLE
Error: get-installed-path: module not found "decentraland" in path

### ISSUE THREAD

**Issue by michaltakac** [decentraland/cli#68]
Seems like on Windows, the `get-installed-path` package doesn't work well - it cannot find the path to where the `cli` is installed (globally):

```
$ dcl help
C:\Users\Takacovci\AppData\Roaming\nvm\v8.8.1\node_modules\decentraland\node_modules\get-installed-path\dist\index.js:164
    throw new Error(msg);
    ^

Error: get-installed-path: module not found "decentraland" in path C:\Users\Takacovci\AppData\Roaming\npm\node_modules\decentraland
    at getInstalledPathSync (C:\Users\Takacovci\AppData\Roaming\nvm\v8.8.1\node_modules\decentraland\node_modules\get-installed-path\dist\index.js:164:11)
    at Object.<anonymous> (C:\Users\Takacovci\AppData\Roaming\nvm\v8.8.1\node_modules\decentraland\dist\utils\cli-path.js:4:19)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Takacovci\AppData\Roaming\nvm\v8.8.1\node_modules\decentraland\dist\commands\init.js:15:20)
```

OS: Windows 10 64bit
Node: v8.8.1
Using Git Bash.

**Comment by michaltakac** [comment]
The problem was that I used [NVM for Windows](https://github.com/coreybutler/nvm-windows) (NodeJS version manager) and also had the older NodeJS version installed through [official installer](https://nodejs.org/en/download/), which messed up my `NODE_PATH` in Windows `PATH` env variable.

I recommend using official NodeJS installer on Windows. Adding it to readme and pinging docs guys.
