### ISSUE TITLE
DCL Start errors out for smart wearable (Beta) basic configuration

### ISSUE THREAD

**Issue by 5amrun** [decentraland/cli#773]
# What? 

DCL Start errors out for smart wearable (Beta) basic configuration

### The error:

`
Unable to load wearable.json properly, please check it. Error: strict mode: unknown keyword: "_isThirdParty"
    at Object.checkStrictMode (/usr/local/lib/node_modules/decentraland/node_modules/ajv/dist/compile/validate/index.js:183:15)
    at checkUnknownRules (/usr/local/lib/node_modules/decentraland/node_modules/ajv/dist/compile/util.js:32:24)
    at Object.alwaysValidSchema (/usr/local/lib/node_modules/decentraland/node_modules/ajv/dist/compile/util.js:19:5)
    at /usr/local/lib/node_modules/decentraland/node_modules/ajv/dist/vocabularies/applicator/oneOf.js:30:28
    at Array.forEach (<anonymous>)
    at validateOneOf (/usr/local/lib/node_modules/decentraland/node_modules/ajv/dist/vocabularies/applicator/oneOf.js:28:20)
    at CodeGen.code (/usr/local/lib/node_modules/decentraland/node_modules/ajv/dist/compile/codegen/index.js:438:13)
    at CodeGen.block (/usr/local/lib/node_modules/decentraland/node_modules/ajv/dist/compile/codegen/index.js:567:18)
    at Object.code (/usr/local/lib/node_modules/decentraland/node_modules/ajv/dist/vocabularies/applicator/oneOf.js:25:13)
    at Object.keywordCode (/usr/local/lib/node_modules/decentraland/node_modules/ajv/dist/compile/validate/keyword.js:12:13)
`
### To reproduce the issue:
Follow the [official doc](https://docs.decentraland.org/development-guide/smart-wearables/) for smart wearables.

**Comment by 5amrun** [comment]
Got rid of the error by Downgrading:

decentraland to 3.10.0
decentraland-ecs to 6.10.0

But the issue still persists in the latest versions.
